name: 'Run DublokSoftware/Github.Action.Sport'

on:
  # schedule:
  #   - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  action:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        repository: DublokSoftware/Github.Action.Sport
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: ./.github/repository
    - name: Run
      uses: ./.github/repository
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  inform:
    needs: action
    runs-on: ubuntu-latest
    steps:
    - name: Inform
      run: |
        curl --location --request POST 'https://api.github.com/repos/${{ GITHUB_REPOSITORY }}/actions/workflows/${{ GITHUB_ACTION }}/dispatches' \
        --header 'Accept: application/vnd.github+json' \
        --header 'Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
        --header 'X-GitHub-Api-Version: 2022-11-28' \
        --header 'Content-Type: application/json' \
        --data-raw "{\"ref\":\"main\",\"inputs\":{\"reason\":\"Recursive-Call\"}}"
